// Honduras states (departments) and their cities
export interface City {
    name: string;
    isLaCeiba?: boolean;
}

export interface State {
    name: string;
    cities: City[];
}

export const hondurasStates: State[] = [
    {
        name: 'Atlántida',
        cities: [
            { name: 'La Ceiba', isLaCeiba: true },
            { name: 'Tela' },
            { name: 'El Porvenir' },
            { name: 'Jutiapa' },
            { name: 'La Masica' },
            { name: 'Arizona' },
            { name: 'Esparta' },
            { name: 'San Francisco' },
        ],
    },
    {
        name: 'Cortés',
        cities: [
            { name: 'San Pedro Sula' },
            { name: 'Choloma' },
            { name: 'La Lima' },
            { name: 'Omoa' },
            { name: 'Pimienta' },
            { name: 'Potrerillos' },
            { name: 'Puerto Cortés' },
            { name: 'San Antonio de Cortés' },
            { name: 'San Francisco de Yojoa' },
            { name: 'San Manuel' },
            { name: 'Santa Cruz de Yojoa' },
            { name: 'Villanueva' },
        ],
    },
    {
        name: 'Francisco Morazán',
        cities: [
            { name: 'Tegucigalpa' },
            { name: 'Comayagüela' },
            { name: 'Valle de Ángeles' },
            { name: 'Santa Lucía' },
            { name: 'Ojojona' },
            { name: 'Lepaterique' },
            { name: 'San Antonio de Oriente' },
            { name: 'Tatumbla' },
            { name: 'Cantarranas' },
            { name: 'Cedros' },
            { name: 'Curar ado' },
            { name: 'El Porvenir' },
            { name: 'Guaimaca' },
            { name: 'La Libertad' },
            { name: 'La Venta' },
            { name: 'Maraita' },
            { name: 'Marale' },
            { name: 'Nueva Armenia' },
            { name: 'Orica' },
            { name: 'Reitoca' },
            { name: 'Sabanagrande' },
            { name: 'San Buenaventura' },
            { name: 'San Ignacio' },
            { name: 'San Juan de Flores' },
            { name: 'San Miguelito' },
            { name: 'Talanga' },
            { name: 'Vallecillo' },
            { name: 'Villa de San Francisco' },
        ],
    },
    {
        name: 'Yoro',
        cities: [
            { name: 'Yoro' },
            { name: 'El Progreso' },
            { name: 'Olanchito' },
            { name: 'Morazán' },
            { name: 'Arenal' },
            { name: 'El Negrito' },
            { name: 'Jocón' },
            { name: 'Santa Rita' },
            { name: 'Sulaco' },
            { name: 'Victoria' },
            { name: 'Yorito' },
        ],
    },
    {
        name: 'Choluteca',
        cities: [
            { name: 'Choluteca' },
            { name: 'Marcovia' },
            { name: 'San Marcos de Colón' },
            { name: 'El Triunfo' },
            { name: 'Pespire' },
            { name: 'Namasigüe' },
            { name: 'Orocuina' },
            { name: 'San Antonio de Flores' },
            { name: 'Duyure' },
            { name: 'Morolica' },
        ],
    },
    {
        name: 'Colón',
        cities: [
            { name: 'Trujillo' },
            { name: 'Tocoa' },
            { name: 'Bonito Oriental' },
            { name: 'Iriona' },
            { name: 'Limón' },
            { name: 'Sabá' },
            { name: 'Santa Fe' },
            { name: 'Santa Rosa de Aguán' },
            { name: 'Sonaguera' },
            { name: 'Balfate' },
        ],
    },
    {
        name: 'Comayagua',
        cities: [
            { name: 'Comayagua' },
            { name: 'Siguatepeque' },
            { name: 'La Libertad' },
            { name: 'Ajuterique' },
            { name: 'El Rosario' },
            { name: 'Esquías' },
            { name: 'Humuya' },
            { name: 'La Trinidad' },
            { name: 'Lamaní' },
            { name: 'Las Lajas' },
            { name: 'Meámbar' },
            { name: 'Minas de Oro' },
            { name: 'Ojos de Agua' },
            { name: 'San Jerónimo' },
            { name: 'San José de Comayagua' },
            { name: 'San José del Potrero' },
            { name: 'San Luis' },
            { name: 'San Sebastián' },
            { name: 'Taulabé' },
            { name: 'Villa de San Antonio' },
        ],
    },
    {
        name: 'Copán',
        cities: [
            { name: 'Santa Rosa de Copán' },
            { name: 'Copán Ruinas' },
            { name: 'Corquín' },
            { name: 'Cucuyagua' },
            { name: 'Dolores' },
            { name: 'Dulce Nombre' },
            { name: 'El Paraíso' },
            { name: 'Florida' },
            { name: 'La Jigua' },
            { name: 'La Unión' },
            { name: 'Nueva Arcadia' },
            { name: 'San Agustín' },
            { name: 'San Antonio' },
            { name: 'San Jerónimo' },
            { name: 'San José' },
            { name: 'San Juan de Opoa' },
            { name: 'San Nicolás' },
            { name: 'San Pedro' },
            { name: 'Santa Rita' },
            { name: 'Trinidad de Copán' },
            { name: 'Veracruz' },
        ],
    },
    {
        name: 'El Paraíso',
        cities: [
            { name: 'Yuscarán' },
            { name: 'Danlí' },
            { name: 'El Paraíso' },
            { name: 'Alauca' },
            { name: 'Güinope' },
            { name: 'Jacaleapa' },
            { name: 'Liure' },
            { name: 'Morocelí' },
            { name: 'Oropolí' },
            { name: 'Potrerillos' },
            { name: 'San Antonio de Flores' },
            { name: 'San Lucas' },
            { name: 'San Matías' },
            { name: 'Soledad' },
            { name: 'Teupasenti' },
            { name: 'Texiguat' },
            { name: 'Trojes' },
            { name: 'Vado Ancho' },
            { name: 'Yauyupe' },
        ],
    },
    {
        name: 'Gracias a Dios',
        cities: [
            { name: 'Puerto Lempira' },
            { name: 'Brus Laguna' },
            { name: 'Ahuas' },
            { name: 'Juan Francisco Bulnes' },
            { name: 'Villeda Morales' },
            { name: 'Wampusirpe' },
        ],
    },
    {
        name: 'Intibucá',
        cities: [
            { name: 'La Esperanza' },
            { name: 'Jesús de Otoro' },
            { name: 'Camasca' },
            { name: 'Colomoncagua' },
            { name: 'Concepción' },
            { name: 'Dolores' },
            { name: 'Intibucá' },
            { name: 'Magdalena' },
            { name: 'Masaguara' },
            { name: 'San Antonio' },
            { name: 'San Francisco de Opalaca' },
            { name: 'San Isidro' },
            { name: 'San Juan' },
            { name: 'San Marcos de la Sierra' },
            { name: 'San Miguelito' },
            { name: 'Santa Lucía' },
            { name: 'Yamaranguila' },
        ],
    },
    {
        name: 'Islas de la Bahía',
        cities: [
            { name: 'Roatán' },
            { name: 'Utila' },
            { name: 'Guanaja' },
            { name: 'José Santos Guardiola' },
        ],
    },
    {
        name: 'La Paz',
        cities: [
            { name: 'La Paz' },
            { name: 'Marcala' },
            { name: 'Aguanqueterique' },
            { name: 'Cabañas' },
            { name: 'Cane' },
            { name: 'Chinacla' },
            { name: 'Guajiquiro' },
            { name: 'Lauterique' },
            { name: 'Mercedes de Oriente' },
            { name: 'Opatoro' },
            { name: 'San Antonio del Norte' },
            { name: 'San José' },
            { name: 'San Juan' },
            { name: 'San Pedro de Tutule' },
            { name: 'Santa Ana' },
            { name: 'Santa Elena' },
            { name: 'Santa María' },
            { name: 'Santiago de Puringla' },
            { name: 'Yarula' },
        ],
    },
    {
        name: 'Lempira',
        cities: [
            { name: 'Gracias' },
            { name: 'Belén' },
            { name: 'Candelaria' },
            { name: 'Cololaca' },
            { name: 'Erandique' },
            { name: 'Gualcince' },
            { name: 'Guarita' },
            { name: 'La Campa' },
            { name: 'La Iguala' },
            { name: 'La Unión' },
            { name: 'La Virtud' },
            { name: 'Las Flores' },
            { name: 'Lepaera' },
            { name: 'Mapulaca' },
            { name: 'Piraera' },
            { name: 'San Andrés' },
            { name: 'San Francisco' },
            { name: 'San Juan Guarita' },
            { name: 'San Manuel Colohete' },
            { name: 'San Marcos de Caiquín' },
            { name: 'San Rafael' },
            { name: 'San Sebastián' },
            { name: 'Santa Cruz' },
            { name: 'Talgua' },
            { name: 'Tambla' },
            { name: 'Tomalá' },
            { name: 'Valladolid' },
            { name: 'Virginia' },
        ],
    },
    {
        name: 'Ocotepeque',
        cities: [
            { name: 'Ocotepeque' },
            { name: 'Belén Gualcho' },
            { name: 'Concepción' },
            { name: 'Dolores Merendón' },
            { name: 'Fraternidad' },
            { name: 'La Encarnación' },
            { name: 'La Labor' },
            { name: 'Lucerna' },
            { name: 'Mercedes' },
            { name: 'San Fernando' },
            { name: 'San Francisco del Valle' },
            { name: 'San Jorge' },
            { name: 'San Marcos' },
            { name: 'Santa Fe' },
            { name: 'Sensenti' },
            { name: 'Sinuapa' },
        ],
    },
    {
        name: 'Olancho',
        cities: [
            { name: 'Juticalpa' },
            { name: 'Catacamas' },
            { name: 'Campamento' },
            { name: 'Concordia' },
            { name: 'Dulce Nombre de Culmí' },
            { name: 'El Rosario' },
            { name: 'Esquipulas del Norte' },
            { name: 'Gualaco' },
            { name: 'Guarizama' },
            { name: 'Guata' },
            { name: 'Guayape' },
            { name: 'Jano' },
            { name: 'La Unión' },
            { name: 'Mangulile' },
            { name: 'Manto' },
            { name: 'Patuca' },
            { name: 'Salamá' },
            { name: 'San Esteban' },
            { name: 'San Francisco de Becerra' },
            { name: 'San Francisco de la Paz' },
            { name: 'Santa María del Real' },
            { name: 'Silca' },
            { name: 'Yocón' },
        ],
    },
    {
        name: 'Santa Bárbara',
        cities: [
            { name: 'Santa Bárbara' },
            { name: 'Arada' },
            { name: 'Atima' },
            { name: 'Azacualpa' },
            { name: 'Ceguaca' },
            { name: 'Chinda' },
            { name: 'Colinas' },
            { name: 'Concepción del Norte' },
            { name: 'Concepción del Sur' },
            { name: 'El Níspero' },
            { name: 'Gualala' },
            { name: 'Ilama' },
            { name: 'Las Vegas' },
            { name: 'Macuelizo' },
            { name: 'Naranjito' },
            { name: 'Nuevo Celilac' },
            { name: 'Petoa' },
            { name: 'Protección' },
            { name: 'Quimistán' },
            { name: 'San Francisco de Ojuera' },
            { name: 'San José de Colinas' },
            { name: 'San Luis' },
            { name: 'San Marcos' },
            { name: 'San Nicolás' },
            { name: 'San Pedro Zacapa' },
            { name: 'San Vicente Centenario' },
            { name: 'Santa Rita' },
            { name: 'Trinidad' },
        ],
    },
    {
        name: 'Valle',
        cities: [
            { name: 'Nacaome' },
            { name: 'Alianza' },
            { name: 'Amapala' },
            { name: 'Aramecina' },
            { name: 'Caridad' },
            { name: 'Goascorán' },
            { name: 'Langue' },
            { name: 'San Francisco de Coray' },
            { name: 'San Lorenzo' },
        ],
    },
];
